backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "src/data/portfolio"
    create: true
    fields:
      - { name: "title", label: "Title" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "thumbnail", label: "Thumbnail", widget: "image" }
      - { name: "description", label: "Description", widget: "markdown" }
      - { name: "external_link", label: "External link", widget: "string" }
